import { create } from "zustand";
import { persist } from "zustand/middleware";
import { useCallback } from "react";

export type Language = "en" | "id";

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: "id", // default to Indonesian
      setLanguage: (language) => set({ language }),
    }),
    {
      name: "stokku-language",
    }
  )
);

export const translations = {
  en: {
    // Sidebar
    overview: "Overview",
    products: "Products",
    warehouses: "Warehouses",
    inventory: "Inventory",
    transactions: "Transactions",
    intelligence: "Intelligence",
    ai_forecast: "AI Forecast",
    system: "System",
    settings: "Settings",
    logout: "Log Out",
    
    // Header
    search_placeholder: "Search SKU, warehouse, or transaction...",
    alerts_notifications: "Alerts & Notifications",
    critical: "critical",
    loading_alerts: "Loading alerts...",
    all_clear: "All clear!",
    no_alerts: "No critical stock alerts found.",
    low_stock_alerts: "Low Stock Alerts",
    dead_stock_alerts: "Dead Stock Alerts",
    stock_status: "Stock: {qty} / min {min}",
    not_moving: "Stock {qty} pcs not moving 30+ days",
    profile_settings: "Profile & Settings",
    light: "Light",
    dark: "Dark",
    sys_theme: "System",
    
    // Dashboard / Overview
    greeting_morning: "Good morning",
    greeting_afternoon: "Good afternoon",
    greeting_evening: "Good evening",
    happening_today: "Here's what's happening with your inventory today.",
    refresh: "Refresh",
    retry: "Retry",
    inv_value: "Inventory value",
    active_products: "Active products",
    low_stock_alerts_count: "Low stock alerts",
    needs_attention: "Needs attention",
    all_clear_status: "All clear",
    stock_activity: "Stock activity",
    weekly_vol: "Weekly stock-in vs stock-out volume",
    stock_in: "Stock in",
    stock_out: "Stock out",
    quick_insights: "Quick insights",
    restock_needed: "Restock needed",
    projected_run_out: "SKU-LAP-001 is projected to run out within 3 days based on current velocity.",
    demand_trend: "Demand trend",
    forecasted_increase: "Electronics category demand is forecasted to increase 15% next week.",
    dead_stock_card: "Dead stock",
    not_moved_days: "{count} items have not moved in 30+ days.",
    view_all_inv: "View all inventory →",
    critical_badge: "Critical",
    action_col: "Action",
    restock: "Restock",
    product: "Product",
    warehouse: "Warehouse",
    stock: "Stock",
    status: "Status",
    no_low_stock: "No low stock items",
    healthy_levels: "All inventory levels are healthy.",
    
    // Chatbot
    chatbot_title: "Stokku AI Assistant",
    chatbot_input_placeholder: "Ask about inventory, forecast, or stock updates...",
    disclaimer: "Responses are generated by AI. Powered by {model}.",
    clear_chat: "Clear Chat",
    gemma_disclaimer: "Gemma model selected. System prompt prepended to conversation.",
    send: "Send",
    quick_templates: "Quick templates",
    bot_greeting: "Hi! 👋 I'm **Stokku AI**, your inventory assistant. Ask me about stock, restock, dead-stock, or forecasts anytime.",
    quick_reply_1: "What's critical stock today?",
    quick_reply_2: "Get restock recommendation",
    quick_reply_3: "Detect dead-stock",
    quick_reply_4: "Summarize inventory condition",
    chatbot_error_retry: "Sorry, the chatbot is currently unavailable. {error}",
    
    // Login
    login_title: "Sign in to Stokku.ai",
    login_subtitle: "Enter your credentials to access the dashboard",
    email_label: "Email Address",
    password_label: "Password",
    sign_in: "Sign In",
    forgot_password: "Forgot password?",
    invalid_credentials: "Email or password is incorrect",
  },
  id: {
    // Sidebar
    overview: "Ikhtisar",
    products: "Produk",
    warehouses: "Gudang",
    inventory: "Inventaris",
    transactions: "Transaksi",
    intelligence: "Kecerdasan AI",
    ai_forecast: "AI Forecast",
    system: "Sistem",
    settings: "Pengaturan",
    logout: "Keluar",
    
    // Header
    search_placeholder: "Cari SKU, gudang, atau transaksi...",
    alerts_notifications: "Peringatan & Notifikasi",
    critical: "kritis",
    loading_alerts: "Memuat peringatan...",
    all_clear: "Semua aman!",
    no_alerts: "Tidak ada peringatan stok kritis.",
    low_stock_alerts: "Peringatan Stok Menipis",
    dead_stock_alerts: "Peringatan Stok Mati",
    stock_status: "Stok: {qty} / min {min}",
    not_moving: "Stok {qty} pcs tidak bergerak 30+ hari",
    profile_settings: "Profil & Pengaturan",
    light: "Terang",
    dark: "Gelap",
    sys_theme: "Sistem",
    
    // Dashboard / Overview
    greeting_morning: "Selamat pagi",
    greeting_afternoon: "Selamat siang",
    greeting_evening: "Selamat malam",
    happening_today: "Berikut adalah rangkuman kondisi inventaris Anda hari ini.",
    refresh: "Segarkan",
    retry: "Coba Lagi",
    inv_value: "Nilai inventaris",
    active_products: "Produk aktif",
    low_stock_alerts_count: "Stok menipis",
    needs_attention: "Butuh perhatian",
    all_clear_status: "Semua aman",
    stock_activity: "Aktivitas stok",
    weekly_vol: "Volume masuk vs keluar mingguan",
    stock_in: "Stok masuk",
    stock_out: "Stok keluar",
    quick_insights: "Analisis cepat",
    restock_needed: "Perlu restock",
    projected_run_out: "SKU-LAP-001 diproyeksikan habis dalam 3 hari berdasarkan kecepatan saat ini.",
    demand_trend: "Tren permintaan",
    forecasted_increase: "Permintaan kategori Elektronik diprediksi meningkat 15% minggu depan.",
    dead_stock_card: "Stok mati",
    not_moved_days: "{count} produk tidak bergerak dalam 30+ hari.",
    view_all_inv: "Lihat semua inventaris →",
    critical_badge: "Kritis",
    action_col: "Aksi",
    restock: "Restock",
    product: "Produk",
    warehouse: "Gudang",
    stock: "Stok",
    status: "Status",
    no_low_stock: "Tidak ada stok menipis",
    healthy_levels: "Semua tingkat inventaris dalam kondisi sehat.",
    
    // Chatbot
    chatbot_title: "Asisten AI Stokku",
    chatbot_input_placeholder: "Tanyakan tentang stok, forecast, atau transaksi...",
    disclaimer: "Jawaban dihasilkan oleh AI. Didukung oleh {model}.",
    clear_chat: "Bersihkan Obrolan",
    gemma_disclaimer: "Model Gemma dipilih. System prompt disisipkan ke percakapan.",
    send: "Kirim",
    quick_templates: "Pertanyaan cepat",
    bot_greeting: "Halo! 👋 Saya **Stokku AI**, asisten inventaris untuk Stokku.ai. Tanyakan soal stok, restock, dead-stock, atau forecast kapan saja.",
    quick_reply_1: "Apa stok kritis hari ini?",
    quick_reply_2: "Berikan rekomendasi restock",
    quick_reply_3: "Deteksi dead-stock",
    quick_reply_4: "Ringkas kondisi inventaris",
    chatbot_error_retry: "Maaf, chatbot sedang tidak tersedia. {error}",
    
    // Login
    login_title: "Masuk ke Stokku.ai",
    login_subtitle: "Masukkan email dan password untuk mengakses dashboard",
    email_label: "Alamat Email",
    password_label: "Kata Sandi",
    sign_in: "Masuk",
    forgot_password: "Lupa kata sandi?",
    invalid_credentials: "Email atau password salah",
  }
};

export function useTranslation() {
  const { language, setLanguage } = useLanguageStore();

  const t = useCallback(
    (key: keyof typeof translations.en, replacements?: Record<string, string | number>) => {
      let text = translations[language][key] || translations.en[key] || String(key);
      if (replacements) {
        Object.entries(replacements).forEach(([k, v]) => {
          text = text.replace(`{${k}}`, String(v));
        });
      }
      return text;
    },
    [language]
  );

  return { t, language, setLanguage };
}

